import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useProject } from '@/hooks/useProjects';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { ArrowLeft, FileText, Code, Book, CheckCircle2, Clock, Folder, ExternalLink } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';

export default function ProjectDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { data: project, isLoading, error } = useProject(id);
  const [selectedFile, setSelectedFile] = useState(null);
  const [fileContent, setFileContent] = useState('');

  // Simulated project files (in real app, this would come from API)
  const projectFiles = [
    { name: 'README.md', type: 'markdown', path: 'README.md', icon: Book },
    { name: 'plan.md', type: 'markdown', path: '.botuvic/reports/PLAN.md', icon: FileText },
    { name: 'TODO.md', type: 'markdown', path: '.botuvic/reports/TODO.md', icon: CheckCircle2 },
    { name: 'REPORT.md', type: 'markdown', path: '.botuvic/reports/REPORT.md', icon: FileText },
    { name: 'project.json', type: 'json', path: '.botuvic/project.json', icon: Code },
    { name: 'phases.json', type: 'json', path: '.botuvic/phases.json', icon: Code },
    { name: 'progress.json', type: 'json', path: '.botuvic/progress.json', icon: Code },
  ];

  const getStatusColor = (status) => {
    switch (status) {
      case 'active':
        return 'bg-green-500';
      case 'paused':
        return 'bg-yellow-500';
      case 'complete':
        return 'bg-blue-500';
      case 'archived':
        return 'bg-gray-500';
      default:
        return 'bg-gray-500';
    }
  };

  const getStatusLabel = (status) => {
    switch (status) {
      case 'active':
        return 'Active';
      case 'paused':
        return 'Paused';
      case 'complete':
        return 'Complete';
      case 'archived':
        return 'Archived';
      default:
        return status || 'Active';
    }
  };

  const handleFileClick = async (file) => {
    setSelectedFile(file);
    // Simulated file content (in real app, fetch from API)
    setFileContent(`# ${file.name}\n\nThis is the content of ${file.name}.\n\nGenerated by BOTUVIC agent.\n\n## Project Information\n\nProject: ${project?.name || 'Unknown'}\nStatus: ${project?.status || 'active'}\nProgress: ${project?.progress_percentage || 0}%\n\n---\n\n*This file was automatically generated by the BOTUVIC AI agent.*`);
  };

  if (isLoading) {
    return (
      <div className="dashboard-container">
        <div className="dashboard-content">
          <div className="flex items-center justify-center min-h-screen">
            <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </div>
      </div>
    );
  }

  if (error || !project) {
    return (
      <div className="dashboard-container">
        <div className="dashboard-content">
          <div className="px-[25px] py-8">
            <Button onClick={() => navigate('/')} variant="ghost" className="mb-4">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
            <Card className="glass">
              <CardContent className="p-8 text-center text-white/60">
                <p>Project not found</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    );
  }

  const progress = project.progress_percentage || 0;
  const currentPhase = project.current_phase || 1;
  const totalPhases = project.total_phases || 3;
  const techStack = project.tech_stack || [];

  return (
    <div className="dashboard-container">
      <div className="dashboard-content">
        <div className="px-[25px] py-6">
          {/* Header */}
          <div className="mb-6">
            <Button onClick={() => navigate('/')} variant="ghost" className="mb-4 text-white/70 hover:text-white">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-3xl font-bold text-white mb-2">{project.name}</h1>
                {project.description && (
                  <p className="text-white/70">{project.description}</p>
                )}
              </div>
              <span className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-sm font-medium text-white ${getStatusColor(project.status)}`}>
                <span className="w-2 h-2 rounded-full bg-white"></span>
                {getStatusLabel(project.status)}
              </span>
            </div>
          </div>

          {/* Project Info Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
            <Card className="glass">
              <CardHeader>
                <CardTitle className="text-lg text-white">Progress</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-2xl font-bold text-white">{progress}%</span>
                    <span className="text-sm text-white/60">Phase {currentPhase}/{totalPhases}</span>
                  </div>
                  <Progress value={progress} />
                </div>
              </CardContent>
            </Card>

            <Card className="glass">
              <CardHeader>
                <CardTitle className="text-lg text-white">Created</CardTitle>
              </CardHeader>
              <CardContent>
                {project.created_at ? (
                  <div>
                    <div className="text-white text-sm mb-1">
                      {new Date(project.created_at).toLocaleDateString()}
                    </div>
                    <div className="text-white/60 text-xs">
                      {formatDistanceToNow(new Date(project.created_at), { addSuffix: true })}
                    </div>
                  </div>
                ) : (
                  <div className="text-white/60 text-sm">-</div>
                )}
              </CardContent>
            </Card>

            <Card className="glass">
              <CardHeader>
                <CardTitle className="text-lg text-white">Last Updated</CardTitle>
              </CardHeader>
              <CardContent>
                {project.updated_at ? (
                  <div>
                    <div className="text-white text-sm mb-1">
                      {new Date(project.updated_at).toLocaleDateString()}
                    </div>
                    <div className="text-white/60 text-xs">
                      {formatDistanceToNow(new Date(project.updated_at), { addSuffix: true })}
                    </div>
                  </div>
                ) : (
                  <div className="text-white/60 text-sm">-</div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Tech Stack */}
          {techStack.length > 0 && (
            <Card className="glass mb-6">
              <CardHeader>
                <CardTitle className="text-lg text-white">Tech Stack</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex flex-wrap gap-2">
                  {techStack.map((tech, index) => (
                    <span
                      key={index}
                      className="px-3 py-1 bg-white/10 rounded-lg text-sm text-white/80"
                    >
                      {typeof tech === 'string' ? tech : tech.name || JSON.stringify(tech)}
                    </span>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Files and Content */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* File List */}
            <Card className="glass lg:col-span-1">
              <CardHeader>
                <CardTitle className="text-lg text-white flex items-center gap-2">
                  <Folder className="w-5 h-5" />
                  Project Files
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {projectFiles.map((file) => {
                    const Icon = file.icon;
                    return (
                      <button
                        key={file.path}
                        onClick={() => handleFileClick(file)}
                        className={`w-full text-left p-3 rounded-lg transition-colors flex items-center gap-3 ${
                          selectedFile?.path === file.path
                            ? 'bg-white/20 text-white'
                            : 'bg-white/5 hover:bg-white/10 text-white/70 hover:text-white'
                        }`}
                      >
                        <Icon className="w-4 h-4 flex-shrink-0" />
                        <span className="text-sm truncate">{file.name}</span>
                      </button>
                    );
                  })}
                </div>
              </CardContent>
            </Card>

            {/* File Viewer */}
            <Card className="glass lg:col-span-2">
              <CardHeader>
                <CardTitle className="text-lg text-white flex items-center gap-2">
                  <FileText className="w-5 h-5" />
                  {selectedFile ? selectedFile.name : 'Select a file to view'}
                </CardTitle>
              </CardHeader>
              <CardContent>
                {selectedFile ? (
                  <div className="bg-black/30 rounded-lg p-4 h-[600px] overflow-auto">
                    <pre className="text-white/90 text-sm whitespace-pre-wrap font-mono">
                      {fileContent}
                    </pre>
                  </div>
                ) : (
                  <div className="h-[600px] flex items-center justify-center text-white/60">
                    <div className="text-center">
                      <FileText className="w-12 h-12 mx-auto mb-3 opacity-50" />
                      <p>Select a file from the list to view its content</p>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
